version: '3'

services:
  account:
    build:
      context: ./account
      dockerfile: Dockerfile
    volumes:
      - ./account/:/account/
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn server:app --reload --workers 1 --host 0.0.0.0 --port 8081
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_REGION
    env_file:
      - .env
    ports:
      - 8081:8081 
    depends_on:
      - redis
      - db
    restart: "on-failure"

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5433:5432
    restart: "on-failure"
  
  redis:
    image: "redis:latest"
    expose:
      - 6379
    working_dir: /data
    volumes:
      - redis_data:/data
    restart: "on-failure"

volumes:
    postgres_data:
    redis_data:
